# Generated by Django 3.1.2 on 2020-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(max_length=100, null=True, verbose_name='school name'),
        ),
    ]
