# Generated by Django 3.1.2 on 2020-11-08 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='joined_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
