# Generated by Django 3.1.2 on 2020-10-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201018_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circle',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_circle',
            new_name='is_society',
        ),
    ]
