# Generated by Django 3.1.2 on 2020-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201019_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='society_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='society name'),
        ),
    ]
