# Generated by Django 3.1.2 on 2020-11-08 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201108_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='開催日時'),
        ),
    ]
