# Generated by Django 3.1.2 on 2020-11-09 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('info_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='extra_info',
            field=models.ManyToManyField(related_name='exrea_info', to='app.Information'),
        ),
    ]
