# Generated by Django 3.1.2 on 2020-10-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201019_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
