# Generated by Django 3.1.2 on 2020-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201109_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info',
            field=models.CharField(max_length=200),
        ),
    ]
