# Generated by Django 3.1.2 on 2020-10-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='hello@gamil.com', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
